## Import Libraries

In [1]:
import numpy as np

## Scalars

In [3]:
s = 10
print(s)

10


In [4]:
type(s)

int

> ### Addition

In [45]:
s1 = 10
s2 = 5

In [46]:
s1 + s2

15

> ### Difference

In [47]:
s1 - s2

5

## Vector

In [24]:
v = np.array([15, 2, 1999])

In [25]:
v

array([  15,    2, 1999])

In [26]:
type(v)

numpy.ndarray

In [27]:
v.shape

(3,)

In [28]:
v.reshape(3,1)

array([[  15],
       [   2],
       [1999]])

In [29]:
v.reshape(1,3)

array([[  15,    2, 1999]])

> ### Addition

In [48]:
v1 = np.array([1,2,3,4,5])
v2 = np.array([5,4,3,2,1])

In [49]:
v1 + v2

array([6, 6, 6, 6, 6])

In [56]:
v1 + s1

array([11, 12, 13, 14, 15])

> ### Difference

In [50]:
v1 - v2

array([-4, -2,  0,  2,  4])

In [57]:
s1 - v1

array([9, 8, 7, 6, 5])

> ### Transposing

In [79]:
x = np.array([1,2,3])
x

array([1, 2, 3])

In [80]:
x.shape

(3,)

In [81]:
x.T

array([1, 2, 3])

In [82]:
x_reshaped = x.reshape(1,3)
x_reshaped

array([[1, 2, 3]])

In [83]:
x_reshaped.shape

(1, 3)

In [84]:
x_reshaped = x_reshaped.T
x_reshaped

array([[1],
       [2],
       [3]])

In [85]:
x_reshaped.shape

(3, 1)

## Matrices

In [22]:
m = np.array([[15, 2, 1999], [11, 11, 1999]])

In [23]:
m

array([[  15,    2, 1999],
       [  11,   11, 1999]])

In [30]:
type(m)

numpy.ndarray

In [31]:
m.shape

(2, 3)

> ### Addition

In [51]:
m5 = np.array([[22.33,-4.73],[-203.14,1200.02],[4.22,234.1]])
m5

array([[  22.33,   -4.73],
       [-203.14, 1200.02],
       [   4.22,  234.1 ]])

In [52]:
m6 = np.array([[131.13,448.29],[-340.21,1.06],[30.41,424.99]])
m6

array([[ 131.13,  448.29],
       [-340.21,    1.06],
       [  30.41,  424.99]])

In [53]:
m5 + m6

array([[ 153.46,  443.56],
       [-543.35, 1201.08],
       [  34.63,  659.09]])

In [58]:
m5 + s1

array([[  32.33,    5.27],
       [-193.14, 1210.02],
       [  14.22,  244.1 ]])

> ### Difference

In [54]:
m5 - m6

array([[-108.8 , -453.02],
       [ 137.07, 1198.96],
       [ -26.19, -190.89]])

In [59]:
m5 - s1

array([[  12.33,  -14.73],
       [-213.14, 1190.02],
       [  -5.78,  224.1 ]])

> ### Transposing

In [86]:
A = np.array([[5,12,6],[-3,0,14]])
A

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [87]:
A.shape

(2, 3)

In [88]:
A = A.T

In [89]:
A

array([[ 5, -3],
       [12,  0],
       [ 6, 14]])

In [90]:
A.shape

(3, 2)

## Tensor

In [32]:
m1 = np.array([[5,12,6],[-3,0,14]])
m1

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [33]:
m2 = np.array([[9,8,7],[1,3,-5]])
m2

array([[ 9,  8,  7],
       [ 1,  3, -5]])

In [34]:
t = np.array([m1,m2])

In [35]:
t

array([[[ 5, 12,  6],
        [-3,  0, 14]],

       [[ 9,  8,  7],
        [ 1,  3, -5]]])

In [36]:
type(t)

numpy.ndarray

In [37]:
t.shape

(2, 2, 3)

In [38]:
t_manual = np.array([[[9,8,7],[1,3,-5]], [[5,12,6],[-3,0,14]]])

In [39]:
t_manual

array([[[ 9,  8,  7],
        [ 1,  3, -5]],

       [[ 5, 12,  6],
        [-3,  0, 14]]])

In [40]:
type(t_manual)

numpy.ndarray

In [41]:
t_manual.shape

(2, 2, 3)

## Dot product

> ### Scalar * Scalar

In [91]:
np.dot(5,6)

30

> ### Scalar * Vector

In [93]:
x = np.array([2,8,-4])
x

array([ 2,  8, -4])

In [94]:
5*x

array([ 10,  40, -20])

> ### Vector * Vector

In [96]:
x = np.array([2,8,-4])
y = np.array([1,-7,3])
print("X : ", x, '\nY : ', y)

X :  [ 2  8 -4] 
Y :  [ 1 -7  3]


In [97]:
np.dot(x,y)

-66

> ### Scalar * Matrix

In [98]:
A = np.array([[5,12,6],[-3,0,14]])
A

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [99]:
A*7

array([[ 35,  84,  42],
       [-21,   0,  98]])

> ### Metrix * Metrix

In [108]:
A = np.array([[5,12,6],[-3,0,14]])
print("A : \n", A, '\n\n Shape Of A : ', A.shape)

A : 
 [[ 5 12  6]
 [-3  0 14]] 

 Shape Of A :  (2, 3)


In [109]:
B = np.array([[2,-1],[8,0],[3,0]])
print("B : \n", B, '\n\n Shape Of B : ', B.shape)

B : 
 [[ 2 -1]
 [ 8  0]
 [ 3  0]] 

 Shape Of B :  (3, 2)


In [110]:
Z = np.dot(A,B)
print("Z : \n", Z, '\n\n Shape Of Z : ', Z.shape)

Z : 
 [[124  -5]
 [ 36   3]] 

 Shape Of Z :  (2, 2)


In [111]:
C = np.array([[-12,5,-5,1,6],[6,-2,0,0,-3],[10,2,0,8,0],[9,-4,8,3,-6]])
print("C : \n", C, '\n\n Shape Of C : ', C.shape)

C : 
 [[-12   5  -5   1   6]
 [  6  -2   0   0  -3]
 [ 10   2   0   8   0]
 [  9  -4   8   3  -6]] 

 Shape Of C :  (4, 5)


In [112]:
D = np.array([[6,-1],[8,-4],[2,-2],[7,4],[-6,-9]])
print("D : \n", D, '\n\n Shape Of D : ', D.shape)

D : 
 [[ 6 -1]
 [ 8 -4]
 [ 2 -2]
 [ 7  4]
 [-6 -9]] 

 Shape Of D :  (5, 2)


In [114]:
W = np.dot(C, D)
print("W : \n", W, '\n\n Shape Of W : ', W.shape)

W : 
 [[-71 -48]
 [ 38  29]
 [132  14]
 [ 95  57]] 

 Shape Of W :  (4, 2)
